# Uncomment the next line to define a global platform for your project
# platform :ios

target 'QRcodeSelfPickUp' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks

       use_frameworks!

       pod 'swiftScan'
       pod 'IQKeyboardManagerSwift'
end
